language: ruby
sudo: required
dist: trusty

install:
        - sudo apt install sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio python unzip rsync file bc wget git libncurses5-dev

script:
        - make defconfig BR2_DEFCONFIG=./defconfig
        - while true ; do echo "Still building" ; sleep 60 ; done &
        - stupidpid=$!
        - echo 'Build buildroot'
        - make -j4 > >(tee build.log |grep '>>>') 2>&1
        - kill ${stupidpid}
        - echo 'Display end of log'
        - tail -1000 build.log
env:
    global:
          - LANG="en_US.UTF-8"
